
-- Axe 2: Inject few-shot examples into the most critical prompts
-- Target: consulte-lead, copilot-morning-brief, copilot-suggest-tasks, lead-scoring

-- 1. consulte-lead: Add concrete input/output example for lead synthesis
UPDATE public.ai_prompts
SET system_prompt = system_prompt || E'\n\n## 📌 EXEMPLES FEW-SHOT (Référence qualité)\n\n### EXEMPLE 1 — Synthèse Lead complète\n\n**INPUT (données brutes):**\n```\nLead: TechnoPlus SAS | Status: qualified | Score: 72\nNotes contexte: "Budget confirmé 25k€ HT pour POC chatbot. DG favorable, DSI réticent."\nTranscription 15/01: "Nous avons discuté du déploiement. Budget validé en comité. Délai souhaité: mars 2026."\nActivité: 3 emails, 2 réunions, 1 devis envoyé (18 500€ HT)\n```\n\n**OUTPUT ATTENDU:**\n```markdown\n## 🚦 Dashboard\n| Critère | Statut | Détail |\n|---------|--------|--------|\n| Dernière interaction | 🟢 3j | Email relance devis |\n| Budget | 🟢 Confirmé | 25 000€ HT (source: Note contexte #1) |\n| Décideur | 🟠 Partagé | DG favorable, DSI réticent (source: Note contexte #1) |\n| Prochaine étape | 🔴 À définir | Aucune tâche planifiée |\n\n## ⚡ Actions prioritaires\n1. **Planifier call DSI** — Lever la réticence technique (contexte: Note #1)\n2. **Relancer sur devis 18 500€** — Envoyé il y a 5j, sans retour\n3. **Caler POC mars 2026** — Délai confirmé en réunion du 15/01 [1]\n\n## 💰 Données financières\n| Montant | Contexte | Source | Date |\n|---------|----------|--------|------|\n| 25 000€ HT | Budget POC validé en comité | Note contexte #1 + Transcription 15/01 | 15/01/2026 |\n| 18 500€ HT | Devis envoyé | Activité email | 12/01/2026 |\n\n## 📚 Sources\n[1] Transcription réunion 15/01/2026\n[2] Note de contexte utilisateur\n[3] Historique activité CRM\n```\n\n### EXEMPLE 2 — Lead avec peu de données\n\n**INPUT:**\n```\nLead: Dupont SARL | Status: new | Score: 15\nAucune note, aucune transcription, 1 activité (formulaire contact)\n```\n\n**OUTPUT ATTENDU:**\n```markdown\n## 🚦 Dashboard\n| Critère | Statut | Détail |\n|---------|--------|--------|\n| Dernière interaction | 🟠 Nouveau | Formulaire contact |\n| Budget | ❓ [Non spécifié dans les sources] | — |\n| Décideur | ❓ [Non spécifié dans les sources] | — |\n| Prochaine étape | 🔴 À définir | Premier contact nécessaire |\n\n## ⚡ Actions prioritaires\n1. **Premier appel de découverte** — Qualifier le besoin et le budget\n2. **Recherche LinkedIn** — Identifier le décideur\n\n## 📚 Sources\n[1] Formulaire contact (seule source disponible)\n\n> ℹ️ Synthèse limitée : 1 seule source disponible. Enrichissement nécessaire.\n```',
    version = version + 1,
    updated_at = now()
WHERE slug = 'consulte-lead';

-- 2. copilot-morning-brief: Add few-shot example for morning brief
UPDATE public.ai_prompts
SET system_prompt = system_prompt || E'\n\n## 📌 EXEMPLE FEW-SHOT — Morning Brief\n\n**INPUT:**\n```\nTâches du jour: 3 (1 urgent, 2 medium)\nTâches en retard: 2\nRDV: 10h30 TechnoPlus (démo), 14h InnoVert (discovery)\nAlertes inactivité: Lead "BioTech+" inactif 12j [high]\nSanté projets: "Projet Alpha" off_track (3 tâches retard, budget 95%)\nPipeline: TechnoPlus 85/100, InnoVert 42/100\n```\n\n**OUTPUT ATTENDU:**\n```markdown\n# ☀️ Briefing du 09/02/2026\n\n## 🔴 URGENCES (action immédiate)\n- **Projet Alpha en danger** : 3 tâches en retard + budget à 95%. Arbitrage nécessaire aujourd''hui.\n- **BioTech+ silencieux depuis 12j** : Risque de perte. Envoyer un email de relance personnalisé.\n\n## 📅 AGENDA DU JOUR\n| Heure | Client | Type | Préparation |\n|-------|--------|------|-------------|\n| 10h30 | TechnoPlus | Démo | Score 85/100 — Préparer pricing final |\n| 14h00 | InnoVert | Discovery | Score 42/100 — Focus qualification budget |\n\n## ✅ TODO PRIORITAIRE\n1. 🔴 Arbitrer budget Projet Alpha\n2. 🟠 Relancer BioTech+ (12j inactif)\n3. 🟡 Préparer démo TechnoPlus 10h30\n4. 🟡 Qualifier InnoVert avant RDV 14h\n\n## 📊 PIPELINE\n- **TechnoPlus** : 85/100 → Closable cette semaine si pricing OK\n- **InnoVert** : 42/100 → Besoin qualification BANT\n\n## 💡 INSIGHT\nSemaine chargée avec 2 RDV stratégiques. Prioriser la clôture TechnoPlus.\n```',
    version = version + 1,
    updated_at = now()
WHERE slug = 'copilot-morning-brief';

-- 3. copilot-suggest-tasks: Add few-shot for task suggestions
UPDATE public.ai_prompts
SET system_prompt = system_prompt || E'\n\n## 📌 EXEMPLE FEW-SHOT — Suggestions de tâches\n\n**INPUT (contexte lead "TechnoPlus"):**\n```\nDernier contact: il y a 5j (email devis)\nDevis envoyé: 18 500€ HT, sans réponse\nProchain RDV: aucun planifié\nDécideur: DG favorable, DSI réticent\nBudget: 25 000€ confirmé\n```\n\n**OUTPUT ATTENDU:**\n```json\n{\n  "suggestions": [\n    {\n      "title": "Relancer TechnoPlus sur devis 18 500€",\n      "description": "Devis envoyé il y a 5j sans retour. Envoyer un email de relance avec proposition de call pour lever les objections.",\n      "priority": "high",\n      "task_type": "follow_up",\n      "due_in_days": 1,\n      "reasoning": "Un devis sans retour après 5j perd 30% de chances de conversion chaque jour. Action critique."\n    },\n    {\n      "title": "Organiser call technique avec DSI TechnoPlus",\n      "description": "Le DSI est réticent (note contexte). Proposer une session technique de 30min pour démontrer la faisabilité.",\n      "priority": "high",\n      "task_type": "meeting",\n      "due_in_days": 3,\n      "reasoning": "Le blocage DSI est le principal frein à la conversion. Sans son adhésion, le deal est compromis."\n    },\n    {\n      "title": "Préparer POC TechnoPlus pour mars",\n      "description": "Budget validé et deadline mars 2026 confirmée. Rédiger le CDC et planifier les jalons.",\n      "priority": "medium",\n      "task_type": "proposal",\n      "due_in_days": 7,\n      "reasoning": "Anticiper la phase POC pour respecter le délai client de mars 2026."\n    }\n  ]\n}\n```',
    version = version + 1,
    updated_at = now()
WHERE slug = 'copilot-suggest-tasks';

-- 4. lead-scoring: Add few-shot for scoring
UPDATE public.ai_prompts
SET system_prompt = system_prompt || E'\n\n## 📌 EXEMPLE FEW-SHOT — Lead Scoring\n\n**INPUT:**\n```\nLead: TechnoPlus SAS\n- Source: referral\n- Budget déclaré: 25 000€\n- Décideur identifié: DG (favorable)\n- Besoin: chatbot IA interne\n- Timeline: mars 2026\n- 2 réunions, 1 devis envoyé\n- DSI réticent\n```\n\n**OUTPUT ATTENDU:**\n```json\n{\n  "score": 78,\n  "scoring_details": {\n    "budget": {"score": 25, "max": 25, "reason": "Budget 25k€ confirmé et validé en comité"},\n    "authority": {"score": 18, "max": 25, "reason": "DG favorable mais DSI réticent — risque de blocage technique"},\n    "need": {"score": 20, "max": 25, "reason": "Besoin chatbot IA clair et quantifié"},\n    "timeline": {"score": 15, "max": 25, "reason": "Timeline mars 2026 confirmée, réaliste mais serré"}\n  },\n  "recommended_actions": [\n    "Lever le blocage DSI via session technique",\n    "Accélérer la rédaction du CDC pour tenir mars 2026"\n  ],\n  "risk_level": "medium",\n  "primary_risk": "Adhésion DSI non acquise"\n}\n```',
    version = version + 1,
    updated_at = now()
WHERE slug = 'lead-scoring';
